### PR TITLE
Add typing and comply better with PEP 8

### LINKED ISSUE #11: Make Content Filter typed
With Content Filter's upcoming introduction into Carberretta (https://github.com/Carberra/Carberretta/pull/137), making the project typed would ensure some potential CI issues are eradicated. It would also provide better autocompletes for those using and contributing to Content Filter.

This would involve:

- [x] Typing the project to `mypy --strict` standards
- [x] Formatting the project to make `black` happy

This would force a drop in support for Python 3.4, but considering it reached end-of-life in March 2019, that's no big deal.

I'll PR these changes in.

### PR DESCRIPTION
**Pull request by parafoxia**
This PR:

- [x] Adds static typing to Content Filter, bringing it in line with strict Mypy
- [x] Reformats and sorts imports to make both black and isort happy
- [x] BREAKING: Brings the minimum required Python version to 3.6*

All `nosetests` tests have passed on 3.9. Neither nose nor Travis CI support Python 3.10 so functionality on that cannot be properly tested, but in my own limited testing, it does work on 3.10.

*While this is breaking, this would not require a bump to v3.0, as those with Python 3.6 or higher will not see any affect in its operation. Those on 3.4 or 3.5 would only be able to download up to v2.1. A bump to v2.2 would suffice.

### CODE REVIEW

**Review by MrDogeBro — APPROVED** [review]
Wow lots of changes but they all look good. Thanks for doing all of that! I appreciate it so much! Sorry that you had to deal with my slightly messy code base though. And all of the simple formatting stuff looks fine. Just haven't touched the code base in a bit so those types of things haven't been updated. Thanks!

These changes will be released as v2.2.0

**Comment by parafoxia** [comment]
No worries! A lot of those changes probably came in the test file cos black basically rewrote that lmao, but yeah, I think it was about an hour's work, so could've been worse haha.

**Comment by MrDogeBro** [comment]
Oh ok. Looked like a lot more but yeah lol. Thanks again!

**Comment by parafoxia** [comment]
A lot of the typing changes were pretty simple so that helped. It was really about half an hour on like 2 or 3 things haha, then the CI was a bit weird to sort out.

I'm tempted to open another PR at some point to port the Travis stuff to GitHub Actions, and use pytest instead of nose, but I'll deal with that later 😆

**Comment by MrDogeBro** [comment]
Yeah, I need to go though soon and just start working on updating the whole infrastructure for this project, so if you'd like to help with that your more than welcome to.

**Comment by parafoxia** [comment]
Yeah I'll see about it. I've had a lot of practise with infrastructure design with various projects recently so should be able to help with this one 😆

**Pull request merged**
